# Generated by Django 6.0.6 on 2026-06-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Channel',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='channel',
        ),
    ]
